version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: mvn clean test

      - run:
          shell: /bin/bash
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              if [ ! $(git log --name-status HEAD^..HEAD | grep -q '[ci skip]') ]; then
                git config --global user.email "me@tristanburch.com"
                git config --global user.name "Tristan Burch"
                bash .circleci/release.sh
              fi
            fi
